appId: com.sentinel.app
productName: Sentinel
copyright: "Copyright © 2005 Sentinel"

directories:
  output: "../dist-electron"

files:
  - "**/*"

asar: false

publish: null

win:
  target:
    - target: nsis
      arch:
        - x64
  icon: "icons/icon.ico"

nsis:
  oneClick: false
  perMachine: true
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Sentinel
  uninstallDisplayName: Sentinel HR Simulator
  installerIcon: "icons/icon.ico"
  uninstallerIcon: "icons/icon.ico"
  installerHeaderIcon: "icons/icon.ico"
