appId: com.sentinel.app
productName: Sentinel
copyright: "Copyright © 2025 Sentinel"

directories:
  output: "../dist-electron"

files:
  - "**/*"

asar: false

win:
  target:
    - target: nsis
      arch:
        - x64
  icon: "icons/icon.ico"

nsis:
  oneClick: false
  perMachine: true
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Sentinel
  uninstallDisplayName: Sentinel HR Simulator
  installerIcon: "icons/icon.ico"
  uninstallerIcon: "icons/icon.ico"
  installerHeaderIcon: "icons/icon.ico"

mac:
  target:
    - target: dmg
      arch:
        - x64
        - arm64
    - target: zip
      arch:
        - x64
        - arm64
  icon: "icons/icon.png"
  category: public.app-category.business

dmg:
  contents:
    - x: 130
      y: 220
    - x: 410
      y: 220
      type: link
      path: /Applications

linux:
  target:
    - target: AppImage
      arch:
        - x64
    - target: deb
      arch:
        - x64
  icon: "icons"
  category: Utility
